policy:
  approval:
  - preview
  - prod
  - support

approval_rules:

- name: preview
  description: preview-specific files
  if:
    only_changed_files:
      paths:
      - '.*/preview/.*'
  requires:
    count: 0

- name: prod
  description: prod files

  if:
    changed_files:
      paths:
      - '.*/prod/.*'
  requires:
    count: 1
    users: ["aroq"]

  options:
<<<<<<< Updated upstream
    request_review: true
=======
    request_review:
      enabled: true
>>>>>>> Stashed changes
    mode: all-users


- name: support
  description: support files
  if:
    only_changed_files:
      paths:
      - '.support/.*'
  requires:
    count: 1
    users: ["aroq"]
  options:
<<<<<<< Updated upstream
    request_review: true
=======
    request_review:
      enabled: true
>>>>>>> Stashed changes
    mode: all-users
